object Modules {
    const val app = ":app"
    const val core = ":core"
    const val commonJvm = ":common-jvm"
    const val signin = ":features:login:signin"
    const val signup = ":features:login:signup"
    const val intro = ":features:login:intro"
    const val workspaceCreate = ":features:workspace:workspace-create"
    const val workspaceSelect = ":features:workspace:workspace-select"
    const val workspaceAddMember = ":features:workspace:workspace-add-member"
    const val chat = ":features:chat"
    const val thread = ":features:thread"
    const val navigator = ":navigator"
    const val cache = ":data:cache"
    const val network = ":data:network"
    const val repository = ":data:repository"
    const val domain = ":domain"
    const val safe = ":safe"
    const val commonEntity = ":common-entity"
    const val viewInteractor = ":view-interactor"
}
