object Versions {

    const val nav_version = "2.3.5"
    const val androidx_core = "1.7.0"
    const val androidx_appcompat = "1.4.0"
    const val material = "1.4.0"
    const val constraint_layout = "2.1.2"
    const val junit_4 = "4.13.2"
    const val androidx_junit = "1.1.3"
    const val androidx_espresso = "3.4.0"
    const val tools = "7.0.4"
    const val gradle = "1.6.10"
    const val hilt = "2.38.1"
    const val dagger = "2.40.5"
    const val retrofit = "2.9.0"
    const val logging_interceptor = "4.9.3"
    const val moshi = "2.9.0"
    const val timber = "5.0.1"
    const val multidex = "2.0.1"
    const val coroutine = "1.3.9"
    const val java_x = "1"
    const val kotlin_reflect = "1.6.10"
    const val life_cycle_scope = "2.2.0"
    const val view_model_scope = "2.2.0"
    const val kotlin_coroutines = "1.6.0"
    const val store_version = "4.0.1"
    const val gson_converter = "2.9.0"
    const val swipe_refresh = "1.1.0"
    const val auto_image_slider = "1.4.0"
    const val shimmer = "0.5.0"
    const val circle_image_view = "3.1.0"
    const val epoxy = "5.0.0-beta03"
    const val annotation = "1.3.0"
    const val glide = "4.12.0"
    const val room = "2.4.1"
    const val lottie = "3.4.0"

}
